# - name: drop-in directory
#   ansible.builtin.file:
#     path: /etc/systemd/network/05-eth0.network.d/
#     state: directory
#     owner: root
#     group: root
#     mode: '755'
#
# - name: copy custom config
#   ansible.builtin.copy:
#     src: files/01-custom.conf
#     dest: /etc/systemd/network/05-eth0.network.d/01-custom.conf
#     owner: root
#     group: root
#     mode: '644'
#     backup: yes
#   notify: restart systemd-networkd

- include_tasks: packages.yaml
- include_tasks: br0.yaml
- include_tasks: loopback.yaml
