- name: Install packages
  ansible.builtin.apt:
    pkg:
      - fd-find
      - bat
      - git
      - curl
      - gnupg
      - python3-pip
      - python3-setuptools
      - ca-certificates
      - iptables
      - iptables-persistent
      - apt-transport-https

- name: Symlink vim
  ansible.builtin.file:
    src: /usr/bin/vim
    dest: /usr/bin/v
    state: link

- name: Create scripts dir
  ansible.builtin.file:
    path: /root/scripts
    state: directory
    owner: root
    group: root
    mode: "755"

- name: Update one script
  ansible.builtin.copy:
    src: files/script.sh
    dest: /root/scripts/script.sh
    owner: root
    group: root
    mode: "700"
