Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider "vmware_desktop" do |v|
    v.memory = "1024"
    v.cpus = 2
  end
end
