Vagrant.configure("2") do |config|
  (1..1).each do |i|
  config.vm.define "webserver" do |machine|
    machine.vm.box = 'centos/7'
    machine.vm.hostname = "webserver"
    machine.vm.provider "qemu" do |vb|
      vb.name = "webserver_nginx#{i}"
      vb.cpus = '1'
      vb.memory = '512'
    end
  end
  end
end