Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.name = "nginx-server"
    d.image = "nginx:latest"
    d.ports = ["8080:80"]
    d.remains_running = false
    d.has_ssh = false
  end
end
