---
- name: Check disk space
  hosts: all

  tasks:
    - name: Check available disk space
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph / | awk 'NR==2 {print $5}'
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: data

    - name: print resule
      debug:
        msg: "{{ data.stdout, data.stdout_lines, data.stderr }}"
